version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - redapp

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ejemplo
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - redapp

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - redapp

volumes:
  dbdata:

networks:
  redapp:
    driver: bridge
